In [1]:
import numpy as np
import torch
from torch import nn
from torch.nn import functional as F
import numpy as np
import math

# torch.index_select
- 选择某一维度的tensor
- 选择某一维度（切片）的tensor

In [2]:
a = [i for i in range(100)]

In [3]:
a = np.asarray(a)

In [4]:
tensor = torch.from_numpy(a).view(5, 2, 10)
tensor

tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]],

        [[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
         [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]],

        [[80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
         [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [5]:
index = torch.tensor([0])

In [6]:
print(index)

tensor([0])


In [7]:
selected_tensor = torch.index_select(tensor, -2, index)

In [8]:
print(selected_tensor)

tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]],

        [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]],

        [[40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

        [[60, 61, 62, 63, 64, 65, 66, 67, 68, 69]],

        [[80, 81, 82, 83, 84, 85, 86, 87, 88, 89]]])


In [9]:
x = torch.rand(3, 4)

In [10]:
x

tensor([[0.0697, 0.2385, 0.9623, 0.0611],
        [0.0834, 0.1542, 0.1740, 0.9990],
        [0.7038, 0.5267, 0.4194, 0.4288]])

In [11]:
indices = torch.tensor([0, 2])

In [12]:
torch.index_select(x, 0, indices)

tensor([[0.0697, 0.2385, 0.9623, 0.0611],
        [0.7038, 0.5267, 0.4194, 0.4288]])

# nn.Softmax
- 指定某一维度进行softmax

In [13]:
t = torch.rand(2, 3, 4)
t

tensor([[[0.7071, 0.9053, 0.4256, 0.5803],
         [0.5855, 0.6809, 0.7694, 0.9182],
         [0.1617, 0.6889, 0.7708, 0.4785]],

        [[0.4800, 0.3766, 0.6771, 0.2698],
         [0.8760, 0.6773, 0.2868, 0.2355],
         [0.5167, 0.9376, 0.8107, 0.2526]]])

In [14]:
softmax_layer = nn.Softmax(dim=2)
softmax_layer(t)

tensor([[[0.2594, 0.3163, 0.1958, 0.2285],
         [0.2129, 0.2342, 0.2559, 0.2970],
         [0.1693, 0.2869, 0.3113, 0.2324]],

        [[0.2545, 0.2295, 0.3099, 0.2062],
         [0.3446, 0.2825, 0.1912, 0.1816],
         [0.2158, 0.3288, 0.2896, 0.1657]]])

# 生成mask tensor
- 生成下三角矩阵

In [15]:
mask_tensor = torch.ones(0)
batch_size = 2
len_sentence = 10
mask = torch.ones(len_sentence)
for j in range(batch_size):
    for i in range(1, len_sentence + 1):
        masked = mask.clone()
        masked[i:] = 0
        mask_tensor = torch.cat((mask_tensor, masked))
mask_tensor = mask_tensor.contiguous().view(batch_size, len_sentence, -1)
mask_tensor.size()

torch.Size([2, 10, 10])

In [16]:
print(mask_tensor)

tensor([[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
         [1., 1., 1., 1., 1.,

In [17]:
indices

tensor([0, 2])

In [18]:
for idx in range(len_sentence):
    indices = torch.tensor([idx])
    print(torch.index_select(mask_tensor, 1, indices).squeeze().size())

torch.Size([2, 10])
torch.Size([2, 10])
torch.Size([2, 10])
torch.Size([2, 10])
torch.Size([2, 10])
torch.Size([2, 10])
torch.Size([2, 10])
torch.Size([2, 10])
torch.Size([2, 10])
torch.Size([2, 10])


# CrossEntropyLoss与LogSoftmax+NLLLoss

In [20]:
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
print(input)
print(target)
output = loss(input, target)
print(output)
output.backward()

tensor([[-1.0566,  1.9345,  1.3436,  0.3481,  0.9431],
        [ 1.1675, -1.7566, -0.0121,  0.2475,  0.6680],
        [-0.6781, -1.4774, -0.5253,  0.3409, -1.1188]], requires_grad=True)
tensor([0, 3, 3])
tensor(2.1097, grad_fn=<NllLossBackward>)


In [22]:
m = nn.LogSoftmax(dim=1)
loss = nn.NLLLoss()
# input is of size N x C = 3 x 5
input = torch.randn(3, 5, requires_grad=True)
# each element in target has to have 0 <= value < C
target = torch.tensor([1, 0, 4])
print(input)
print(target)
print(m(input))
output = loss(m(input), target)
print(output)
output.backward()

tensor([[-1.0592, -0.0566, -1.2997,  1.2341, -0.0224],
        [-1.4273,  3.8621,  0.1187, -1.7831,  1.5065],
        [ 0.4038,  0.4911,  1.7940,  1.5893, -2.5623]], requires_grad=True)
tensor([1, 0, 4])
tensor([[-2.8472, -1.8445, -3.0877, -0.5539, -1.8103],
        [-5.4091, -0.1196, -3.8630, -5.7649, -2.4753],
        [-2.2440, -2.1567, -0.8538, -1.0585, -5.2100]],
       grad_fn=<LogSoftmaxBackward>)
tensor(4.1545, grad_fn=<NllLossBackward>)


# argmax

In [30]:
a = torch.rand(3, 4)
a

tensor([[0.8753, 0.5491, 0.0331, 0.4996],
        [0.9131, 0.0492, 0.0030, 0.3543],
        [0.2314, 0.9901, 0.4048, 0.7744]])

In [31]:
print(torch.max(a, 0))

(tensor([0.9131, 0.9901, 0.4048, 0.7744]), tensor([1, 2, 2, 2]))


In [32]:
print(torch.max(a, 1))

(tensor([0.8753, 0.9131, 0.9901]), tensor([0, 0, 1]))


In [33]:
value, index = torch.max(a, 1)
print(index)

tensor([0, 0, 1])


In [3]:
test = torch.rand(3, 4, 5)
test

tensor([[[0.5779, 0.0228, 0.1687, 0.9010, 0.6702],
         [0.6086, 0.5309, 0.1080, 0.0668, 0.3812],
         [0.0454, 0.3512, 0.0306, 0.5432, 0.9805],
         [0.5338, 0.8336, 0.3730, 0.3329, 0.0814]],

        [[0.5210, 0.3601, 0.8037, 0.7082, 0.2501],
         [0.4944, 0.2183, 0.3825, 0.9565, 0.6144],
         [0.3886, 0.0607, 0.6560, 0.5447, 0.4024],
         [0.6622, 0.0506, 0.6926, 0.3241, 0.0444]],

        [[0.3918, 0.0719, 0.7239, 0.0626, 0.2118],
         [0.7054, 0.2246, 0.0483, 0.5243, 0.4974],
         [0.7835, 0.7158, 0.3009, 0.4030, 0.7576],
         [0.5373, 0.7899, 0.9094, 0.5904, 0.2565]]])

In [6]:
test_max = torch.max(test, 2)[1]
test_max

tensor([[3, 0, 4, 1],
        [2, 3, 2, 2],
        [2, 0, 0, 2]])

# torch.cat
- 拼接

In [34]:
b = torch.rand(3, 1)
b

tensor([[0.8450],
        [0.8190],
        [0.2952]])

In [35]:
a = torch.cat([a, b], dim=1)
a

tensor([[0.8753, 0.5491, 0.0331, 0.4996, 0.8450],
        [0.9131, 0.0492, 0.0030, 0.3543, 0.8190],
        [0.2314, 0.9901, 0.4048, 0.7744, 0.2952]])

# 测试mask tensor

In [36]:
BATCH_SIZE = 3
TGT_LENGTH = 5

In [37]:
def create_mask_tensor():
    mask_tensor = torch.ones(0)
    batch_size = BATCH_SIZE
    len_sentence = TGT_LENGTH
    mask = torch.ones(len_sentence)
    for _ in range(batch_size):
        for i in range(1, len_sentence + 1):
            masked = mask.clone()
            masked[i:] = 0
            mask_tensor = torch.cat((mask_tensor, masked))
    mask_tensor = mask_tensor.contiguous().view(batch_size, len_sentence, -1)
    return mask_tensor.long()

In [38]:
mask_tensor = create_mask_tensor()

In [39]:
decoder_input = torch.rand(BATCH_SIZE, TGT_LENGTH)
decoder_input

tensor([[0.5252, 0.9991, 0.3711, 0.2532, 0.1747],
        [0.4516, 0.6943, 0.3076, 0.4729, 0.3486],
        [0.7473, 0.0019, 0.6713, 0.1961, 0.2698]])

In [40]:
decoder_output = torch.rand(BATCH_SIZE * 1).contiguous().view(-1, 1)
decoder_output

tensor([[0.3663],
        [0.6347],
        [0.0095]])

In [41]:
decoder_input[:, 1:2] = decoder_output
decoder_input

tensor([[0.5252, 0.3663, 0.3711, 0.2532, 0.1747],
        [0.4516, 0.6347, 0.3076, 0.4729, 0.3486],
        [0.7473, 0.0095, 0.6713, 0.1961, 0.2698]])

In [42]:
decoder_input[:, 0:3]

tensor([[0.5252, 0.3663, 0.3711],
        [0.4516, 0.6347, 0.3076],
        [0.7473, 0.0095, 0.6713]])

In [43]:
for i in range(TGT_LENGTH):
    mask_cur = mask_tensor[:, i].squeeze().float()
    print(torch.mul(decoder_input, mask_cur))

tensor([[0.5252, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4516, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.7473, 0.0000, 0.0000, 0.0000, 0.0000]])
tensor([[0.5252, 0.3663, 0.0000, 0.0000, 0.0000],
        [0.4516, 0.6347, 0.0000, 0.0000, 0.0000],
        [0.7473, 0.0095, 0.0000, 0.0000, 0.0000]])
tensor([[0.5252, 0.3663, 0.3711, 0.0000, 0.0000],
        [0.4516, 0.6347, 0.3076, 0.0000, 0.0000],
        [0.7473, 0.0095, 0.6713, 0.0000, 0.0000]])
tensor([[0.5252, 0.3663, 0.3711, 0.2532, 0.0000],
        [0.4516, 0.6347, 0.3076, 0.4729, 0.0000],
        [0.7473, 0.0095, 0.6713, 0.1961, 0.0000]])
tensor([[0.5252, 0.3663, 0.3711, 0.2532, 0.1747],
        [0.4516, 0.6347, 0.3076, 0.4729, 0.3486],
        [0.7473, 0.0095, 0.6713, 0.1961, 0.2698]])


# 测试SOS符号

In [44]:
decoder_input = torch.tensor(
    [0 for _ in range(TGT_LENGTH * BATCH_SIZE)]).contiguous().view(
        BATCH_SIZE, TGT_LENGTH)
decoder_input[:, 0] = torch.tensor([3 for _ in range(BATCH_SIZE)])
print(decoder_input)

tensor([[3, 0, 0, 0, 0],
        [3, 0, 0, 0, 0],
        [3, 0, 0, 0, 0]])


# 测试mask convolution(casual convolution)

In [56]:
class MaskConv1d(nn.Conv1d):
    """Masked Conv Kernel for Temporal Convolution"""

    def __init__(self, in_channels, out_channels, kernel_size, stride, padding,
                 dilation):
        super().__init__(in_channels, out_channels, kernel_size, stride,
                         padding, dilation)
        self.mask = torch.tensor([
            0 for _ in range(self.out_channels * self.in_channels *
                             self.kernel_size[0])
        ])
        for idx in range(self.out_channels * self.in_channels *
                         self.kernel_size[0])[::self.kernel_size[0]]:
            for jdx in range(1 + self.kernel_size[0] // 2):
                self.mask[idx + jdx] = 1
        self.mask = self.mask.contiguous().view(
            self.out_channels, self.in_channels, self.kernel_size[0]).float()

    def forward(self, x):
        return F.conv1d(
            input=x,
            weight=self.weight * self.mask,
            stride=self.stride,
            padding=self.padding,
            dilation=self.dilation)

    def show_mask(self):
        return self.mask

    def show_kernel(self):
        return self.weight

    def show_masked_kernel(self):
        return self.mask * self.weight

In [57]:
def MaskedWeightNormalizedConv1d(in_channels, out_channels, kernel_size,
                                 stride, padding, dropout, dilation):
    """Weight-normalized Conv1d layer"""
    m = MaskConv1d(in_channels, out_channels, kernel_size, stride, padding,
                   dilation)
    std = math.sqrt((4 * (1.0 - dropout)) / (m.kernel_size[0] * in_channels))
    nn.init.normal_(m.weight, mean=0, std=std)
    nn.init.constant_(m.bias, 0)
    return nn.utils.weight_norm(m, dim=2)

In [70]:
in_channels = 1
out_channels = 1
kernel_size = 5
stride = 1
padding = 2
dropout = 0
dilation = 1
length = 5
batch = 2

In [71]:
test_conv = MaskedWeightNormalizedConv1d(
    in_channels, out_channels, kernel_size, stride, padding, dropout, dilation)

In [72]:
test_input = torch.rand(batch, in_channels, length)
test_input

tensor([[[0.9078, 0.6385, 0.4975, 0.5884, 0.2787]],

        [[0.2476, 0.4939, 0.1485, 0.5653, 0.7630]]])

In [73]:
test_output = test_conv(test_input)
test_output

tensor([[[ 0.1644,  0.3542, -0.1009, -0.0151,  0.0085]],

        [[ 0.0449,  0.1545,  0.0588, -0.0538,  0.2280]]],
       grad_fn=<SqueezeBackward1>)

In [74]:
test_output[:, :, 2].view(batch, out_channels, 1)

tensor([[[-0.1009]],

        [[ 0.0588]]], grad_fn=<ViewBackward>)

# 可以更改conv的pad，不影响参数

In [75]:
print(type(test_conv.padding))
print(test_conv.padding)
test_conv.padding = (0, )
print(test_conv.padding)

<class 'tuple'>
(2,)
(0,)


In [76]:
test_output = test_conv(test_input)
print(test_output)
print(test_output.size())

tensor([[[-0.1009]],

        [[ 0.0588]]], grad_fn=<SqueezeBackward1>)
torch.Size([2, 1, 1])


In [77]:
test_conv.show_mask()

tensor([[[1., 1., 1., 0., 0.]]])

In [78]:
test_conv.show_kernel()

tensor([[[-0.3953,  0.2628,  0.1811, -0.5356,  0.4858]]],
       grad_fn=<MulBackward0>)

In [79]:
test_conv.show_masked_kernel()

tensor([[[-0.3953,  0.2628,  0.1811, -0.0000,  0.0000]]],
       grad_fn=<MulBackward0>)

# 手动padding

In [98]:
tobepad = torch.rand(batch_size, length)
tobepad

tensor([[0.3862, 0.2712, 0.9297, 0.3981, 0.9489],
        [0.5575, 0.5722, 0.8449, 0.9282, 0.7581]])

In [99]:
pad = torch.zeros(batch_size, padding)
pad

tensor([[0., 0.],
        [0., 0.]])

In [100]:
padded = torch.cat([pad, tobepad, pad], dim=1)
padded

tensor([[0.0000, 0.0000, 0.3862, 0.2712, 0.9297, 0.3981, 0.9489, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.5575, 0.5722, 0.8449, 0.9282, 0.7581, 0.0000, 0.0000]])

# 截取kernel_size window

In [101]:
for i in range(length):
    print(padded[:, i:i + kernel_size])

tensor([[0.0000, 0.0000, 0.3862, 0.2712, 0.9297],
        [0.0000, 0.0000, 0.5575, 0.5722, 0.8449]])
tensor([[0.0000, 0.3862, 0.2712, 0.9297, 0.3981],
        [0.0000, 0.5575, 0.5722, 0.8449, 0.9282]])
tensor([[0.3862, 0.2712, 0.9297, 0.3981, 0.9489],
        [0.5575, 0.5722, 0.8449, 0.9282, 0.7581]])
tensor([[0.2712, 0.9297, 0.3981, 0.9489, 0.0000],
        [0.5722, 0.8449, 0.9282, 0.7581, 0.0000]])
tensor([[0.9297, 0.3981, 0.9489, 0.0000, 0.0000],
        [0.8449, 0.9282, 0.7581, 0.0000, 0.0000]])


# 对输入遮罩

In [4]:
BATCH_SIZE = 2
TGT_LENGTH = 10

In [13]:
def create_mask_tensor():
    mask_tensor = torch.ones(0)
    batch_size = BATCH_SIZE
    len_sentence = TGT_LENGTH
    mask = torch.ones(len_sentence)
    for _ in range(batch_size):
        for i in range(1, len_sentence + 1):
            masked = mask.clone()
            masked[i:] = 0
            mask_tensor = torch.cat((mask_tensor, masked))
    mask_tensor = mask_tensor.contiguous().view(batch_size, len_sentence, -1)
    return mask_tensor.float()

In [14]:
tensor = create_mask_tensor()
tensor

tensor([[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
         [1., 1., 1., 1., 1.,

In [15]:
decoder_input = torch.rand(BATCH_SIZE, TGT_LENGTH)
decoder_input

tensor([[0.8405, 0.5304, 0.2681, 0.9319, 0.2750, 0.5874, 0.1204, 0.6949, 0.5254,
         0.1678],
        [0.6121, 0.8481, 0.3573, 0.6426, 0.7382, 0.0970, 0.2095, 0.7629, 0.5735,
         0.7271]])

In [17]:
for i in range(TGT_LENGTH):
    print(torch.mul(decoder_input, tensor[:, i, :]))

tensor([[0.8405, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.6121, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000]])
tensor([[0.8405, 0.5304, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.6121, 0.8481, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000]])
tensor([[0.8405, 0.5304, 0.2681, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.6121, 0.8481, 0.3573, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000]])
tensor([[0.8405, 0.5304, 0.2681, 0.9319, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.6121, 0.8481, 0.3573, 0.6426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000]])
tensor([[0.8405, 0.5304, 0.2681, 0.9319, 0.2750, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.6121, 0.8481, 0.3573, 0.6426, 0.7382, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000]])
tenso

# 制造decoder input

In [22]:
decoder_input = torch.zeros(BATCH_SIZE, TGT_LENGTH)
decoder_input

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
STR_tensor = torch.Tensor([3 for _ in range(BATCH_SIZE)]).view(BATCH_SIZE, -1)
STR_tensor

tensor([[3.],
        [3.]])

In [27]:
decoder_input[:, 0:1] = STR_tensor
decoder_input

tensor([[3., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [3., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
a = np.ones((5, 4))
b = np.ones((5, 4))
a[2][1] = 5
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 5., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
a - b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 4., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.sum(a - b == 0)

19

# 测试位置向量

In [6]:
batch_size = 5
src_len = 10

src = torch.rand([batch_size, src_len])
src

tensor([[0.5443, 0.9662, 0.9008, 0.9928, 0.3107, 0.8706, 0.5317, 0.4988, 0.0920,
         0.4401],
        [0.2166, 0.3920, 0.0272, 0.6028, 0.3210, 0.0517, 0.8247, 0.7107, 0.3425,
         0.9767],
        [0.0037, 0.0592, 0.8570, 0.0563, 0.1343, 0.8355, 0.3407, 0.5985, 0.7746,
         0.1776],
        [0.7340, 0.7665, 0.1606, 0.2732, 0.8007, 0.5539, 0.0534, 0.3662, 0.2628,
         0.3285],
        [0.4755, 0.7042, 0.6575, 0.5365, 0.3329, 0.6098, 0.6248, 0.5152, 0.8622,
         0.7497]])

In [8]:
pos = torch.arange(0, src.shape[1]).unsqueeze(0).repeat(src.shape[0], 1)
pos

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

# Teacher Forcing Mask Matrix|

In [2]:
ratio = 0.7

In [3]:
m = torch.tensor(
    [1 if np.random.uniform() < ratio else 0 for _ in range(3 * 7)]).view(
        3, 7)

m

tensor([[1, 0, 1, 1, 1, 0, 0],
        [1, 1, 1, 0, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 0]])

In [4]:
1 - m

tensor([[0, 1, 0, 0, 0, 1, 1],
        [0, 0, 0, 1, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 1]])

In [5]:
m.view(-1)

tensor([1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0])

# CosineLoss

In [55]:
# loss = torch.nn.CosineEmbeddingLoss()
loss = torch.nn.L1Loss()

In [56]:
s1 = torch.rand(2, 3, 4)
s2 = torch.rand(2, 3, 4)

In [57]:
s1

tensor([[[0.2294, 0.6706, 0.8194, 0.5345],
         [0.5669, 0.7164, 0.2822, 0.1149],
         [0.0691, 0.6952, 0.3044, 0.2712]],

        [[0.4037, 0.9817, 0.1375, 0.1767],
         [0.0410, 0.2716, 0.2668, 0.9205],
         [0.5496, 0.6949, 0.2812, 0.7154]]])

In [61]:
s2 = torch.rand(2, 3, 4)
# s2[1,:,:] = s1[1,:,:]
s2

tensor([[[0.3198, 0.9845, 0.6231, 0.6462],
         [0.3368, 0.2201, 0.3435, 0.7971],
         [0.4068, 0.4498, 0.8892, 0.2248]],

        [[0.9630, 0.3430, 0.6652, 0.8348],
         [0.9958, 0.6658, 0.6889, 0.6883],
         [0.2694, 0.8085, 0.7882, 0.4452]]])

In [62]:
target = torch.tensor([1.0])

In [63]:
print(loss(s1, s2))

tensor(0.3731)


# 测试交叉熵损失

In [2]:
loss = torch.nn.CrossEntropyLoss(ignore_index=0)

In [3]:
score = torch.rand(3, 4)
score

tensor([[0.5272, 0.4321, 0.0036, 0.3344],
        [0.3667, 0.1570, 0.0063, 0.4954],
        [0.4731, 0.7873, 0.2552, 0.4707]])

In [8]:
target = torch.tensor([0, 1, 2])
target

tensor([0, 1, 2])

In [9]:
print(loss(score, target))

tensor(1.5746)


In [10]:
print(F.softmax(score, dim=1))

tensor([[0.3006, 0.2734, 0.1781, 0.2479],
        [0.2743, 0.2224, 0.1913, 0.3120],
        [0.2398, 0.3283, 0.1928, 0.2392]])


# 测试单词重复度

In [13]:
train_predicted = torch.tensor([1, 4, 2, 6, 5, 1, 7, 9])
train_predicted

tensor([1, 4, 2, 6, 5, 1, 7, 9])

In [14]:
target = torch.tensor([5, 99, 124, 5123, 7, 5123, 5123, 6])
target

tensor([   5,   99,  124, 5123,    7, 5123, 5123,    6])

In [15]:
target = target.numpy()
target

array([   5,   99,  124, 5123,    7, 5123, 5123,    6])

In [16]:
target_set = set(target)
target_set

{5, 6, 7, 99, 124, 5123}

In [17]:
for item in train_predicted.numpy():
    if item in target_set:
        print(item)

6
5
7


In [1]:
import numpy as np

In [8]:
a = np.random.rand(3, 5)
a

array([[0.17944709, 0.72023635, 0.8314441 , 0.79787177, 0.07537743],
       [0.51861272, 0.0243257 , 0.20140041, 0.09965711, 0.44205034],
       [0.25953284, 0.54369564, 0.31343503, 0.51842928, 0.47573975]])

In [9]:
b = a.reshape(-1)
b

array([0.17944709, 0.72023635, 0.8314441 , 0.79787177, 0.07537743,
       0.51861272, 0.0243257 , 0.20140041, 0.09965711, 0.44205034,
       0.25953284, 0.54369564, 0.31343503, 0.51842928, 0.47573975])

# fairseq 创建mask
- B:2
- T:10
- C:7

In [2]:
src_token = torch.tensor(
    [3, 4, 6, 2, 5, 9, 7, 1, 1, 1, 5, 6, 9, 10, 3, 1, 1, 1, 1, 1]).view(2, -1)
src_token

tensor([[ 3,  4,  6,  2,  5,  9,  7,  1,  1,  1],
        [ 5,  6,  9, 10,  3,  1,  1,  1,  1,  1]])

In [3]:
padding_idx = 1

In [4]:
encoder_padding_mask = src_token.eq(padding_idx)
encoder_padding_mask

tensor([[0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
        [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]], dtype=torch.uint8)

In [5]:
x = torch.rand(2, 10, 7)
x

tensor([[[0.2879, 0.1935, 0.3467, 0.4936, 0.3641, 0.1455, 0.4909],
         [0.8279, 0.6078, 0.7099, 0.3670, 0.9470, 0.9482, 0.4308],
         [0.3648, 0.0888, 0.1055, 0.6115, 0.2782, 0.8372, 0.7488],
         [0.2701, 0.5403, 0.5000, 0.8872, 0.0840, 0.7430, 0.9404],
         [0.9012, 0.0188, 0.4205, 0.1322, 0.3403, 0.8259, 0.3328],
         [0.9046, 0.3582, 0.1476, 0.5289, 0.6857, 0.4018, 0.6467],
         [0.0641, 0.3216, 0.2822, 0.8222, 0.8938, 0.4686, 0.6488],
         [0.7104, 0.1159, 0.7566, 0.6550, 0.7744, 0.6454, 0.9690],
         [0.1321, 0.1088, 0.4873, 0.4441, 0.2302, 0.8483, 0.9391],
         [0.2391, 0.9233, 0.3242, 0.6668, 0.4198, 0.8529, 0.2679]],

        [[0.2376, 0.2255, 0.5122, 0.3859, 0.5032, 0.8713, 0.4064],
         [0.1924, 0.1757, 0.8009, 0.5591, 0.0301, 0.5399, 0.0099],
         [0.7599, 0.3510, 0.9313, 0.7132, 0.0521, 0.6284, 0.2873],
         [0.8025, 0.2292, 0.1501, 0.3763, 0.3194, 0.1599, 0.1662],
         [0.5125, 0.9145, 0.8805, 0.2962, 0.5876, 0.8989, 0.

In [6]:
encoder_padding_mask.unsqueeze(-1)

tensor([[[0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [1],
         [1],
         [1]],

        [[0],
         [0],
         [0],
         [0],
         [0],
         [1],
         [1],
         [1],
         [1],
         [1]]], dtype=torch.uint8)

In [7]:
print(x.size())
print(encoder_padding_mask.size())
x = x.masked_fill(encoder_padding_mask.unsqueeze(-1), 0)
x

tensor([[[0.2879, 0.1935, 0.3467, 0.4936, 0.3641, 0.1455, 0.4909],
         [0.8279, 0.6078, 0.7099, 0.3670, 0.9470, 0.9482, 0.4308],
         [0.3648, 0.0888, 0.1055, 0.6115, 0.2782, 0.8372, 0.7488],
         [0.2701, 0.5403, 0.5000, 0.8872, 0.0840, 0.7430, 0.9404],
         [0.9012, 0.0188, 0.4205, 0.1322, 0.3403, 0.8259, 0.3328],
         [0.9046, 0.3582, 0.1476, 0.5289, 0.6857, 0.4018, 0.6467],
         [0.0641, 0.3216, 0.2822, 0.8222, 0.8938, 0.4686, 0.6488],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.2376, 0.2255, 0.5122, 0.3859, 0.5032, 0.8713, 0.4064],
         [0.1924, 0.1757, 0.8009, 0.5591, 0.0301, 0.5399, 0.0099],
         [0.7599, 0.3510, 0.9313, 0.7132, 0.0521, 0.6284, 0.2873],
         [0.8025, 0.2292, 0.1501, 0.3763, 0.3194, 0.1599, 0.1662],
         [0.5125, 0.9145, 0.8805, 0.2962, 0.5876, 0.8989, 0.

# fairseq生成位置向量

In [5]:
src_token = torch.tensor(
    [3, 4, 6, 2, 5, 9, 7, 0, 0, 0, 5, 6, 9, 10, 3, 0, 0, 0, 0, 0]).view(2, -1).long()
src_token

tensor([[ 3,  4,  6,  2,  5,  9,  7,  0,  0,  0],
        [ 5,  6,  9, 10,  3,  0,  0,  0,  0,  0]])

In [6]:
mask = src_token.ne(0).long()
mask

tensor([[1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]])

In [8]:
torch.cumsum(mask, dim=1) * mask + 0

tensor([[1, 2, 3, 4, 5, 6, 7, 0, 0, 0],
        [1, 2, 3, 4, 5, 0, 0, 0, 0, 0]])

In [2]:
B = 8
Tg = 10
decoder_input = torch.zeros(B,Tg)
decoder_input

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [3]:
decoder_input[:,0] = 3
decoder_input

tensor([[3., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [3., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [3., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [3., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [3., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [3., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [3., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [3., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])